FROM node:20-alpine AS base
FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY package.json package-lock.json* ./
RUN yarn install --frozen-lockfile

FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .
ENV APP_ENV=testing
ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN yarn build

CMD npm run test