export const socialMediaName: Record<string, string> = {
  facebook: "Facebook",
  instagram: "Instagram",
  linkedin: "Linkedin",
  twitter: "X",
  tiktok: "Tiktok",
  xing: "Xing",
  telegram: "Telegram",
  skype: "Skype",
  truecaller: "Truecaller",
  icq: "Icq",
  sporttracks: "Sporttracks",
  runkeeper: "Runkeeper",
  goodreads: "Goodreads",
  garminconnect: "Garminconnect",
  deezer: "Deezer",
  flickr: "Flickr",
  fitbit: "Fitbit",
  duolingo: "Duolingo",
  adidas: "Adidas",
  pulsstory: "Pulsstory",
  gravatar: "Gravatar",
  foursquare: "Foursquare",
  vivino: "Vivino",
  aboutme: "Aboutme",
  bitbucket: "Bitbucket",
  apple: "Apple",
  askfm: "Askfm",
  dropbox: "Dropbox",
  google: "Google",
  youtube: "Youtube",
  khanacademy: "Khan Academy",
  strava: "Strava",
  medium: "Medium",
  notion: "Notion",
  eumw: "EU Most Wanted",
  interpol: "Interpol",
  wattpad: "Wattpad",
  scribd: "Scribd",
  edx: "edX",
  teamtreehouse: "Team Treehouse",
  datacamp: "DataCamp",
  academia: "Academia",
  scholar: "Scholar",
  babelio: "Babelio",
  wikipedia: "Wikipedia",
  inkitt: "Inkitt",
  github: "Github",
  yelp: "Yelp",
  myfitnesspal: "My Fitness Pal",
  ebay: "eBay",
  paypal: "PayPal",
  microsoft: "Microsoft",
  samsung: "Samsung",
  web: "Web",
  deepweb: "Deep Web",
  darkweb: "Dark Web",
  bluesky: "Bluesky",
  snapchat: "Snapchat",
  whatsapp: "Whatsapp",
};
