import { searchPersonsQuery } from "@/constants/search";
import { SubjectsState } from "./subjects.types";

export const initialSubjectsState: SubjectsState = {
  subjects: [],
  projectSubjectsBasicInfo: [],
  currentSelectedSubjects: [],
  allProjectsSelectedSubjects: [],
  subjectListPage: 1,
  subjectListPageSize: 5,
  subjectListTotal: 0,
  subjectListTotalPages: 0,
  loading: false,
  error: null,
  searchQuery: searchPersonsQuery,
  currentSubjectData: null,
  currentSubjectDataHash: "",
  currentSubjectRedFlags: null,
  currentSubjectEvaluation: null,
  currentSubjectAlerts: null,
  totalRisks: 0,
  totalAnalyzed: 0,
  totalPersons: 0,
  totalRedFlags: 0,
  evaluationDashPage: "PERSONAL DATA",
  subjectRanking: [],
  subjectAnalysis: null,
  cardView: false,
  webSearch: [],
  exporting: false,
  exportingError: null,
  isAllSelected: false,
  subjectsLoading: false,
};
