import { Person } from "@/types/person/index.interface";
import { defaultPerson } from "./defaultPerson.mock";

export const firstMergedPerson = {
  ...defaultPerson,
  posts: [
    {
      twitter_post_likes_count: undefined,
      twitter_post_quoted_status: undefined,
      twitter_post_language: undefined,
      twitter_post_quotes_count: undefined,
      twitter_post_replies_count: undefined,
      twitter_post_retweets_count: undefined,
      twitter_post_retweeted_status: undefined,
      twitter_post_author_user_id: undefined,
      twitter_post_possibly_sensitive: undefined,
      twitter_post_card: undefined,
      twitter_post_photo: undefined,
      twitter_post_hashtags: undefined,
      twitter_post_symbols: undefined,
      twitter_post_urls: undefined,
      twitter_post_view_count: undefined,
      twitter_post_id: undefined,
      twitter_post_text: undefined,
      twitter_retweeted_post: undefined,
      twitter_quoted_post: undefined,
      verified: false,
      linkedin_post_text: undefined,
      linkedin_post_publishment_date: undefined,
      linkedin_post_comments_count: undefined,
      linkedin_post_likes_count: undefined,
      linkedin_post_shares_count: undefined,
      linkedin_post_photo: undefined,
      linkedin_post_url: undefined,
      reactions: [],
      post_reaction: undefined,
      shared_post: undefined,
      instagram_post_text: undefined,
      instagram_post_id: undefined,
      instagram_user_id: undefined,
      instagram_post_location: undefined,
      instagram_post_likes_count: undefined,
      post_likers: undefined,
      instagram_post_photo: undefined,
      fb_post_text: undefined,
      fb_post_language: undefined,
      fb_post_translated_to: undefined,
      post_translation: undefined,
      fb_post_external_webpages: undefined,
      fb_post_comments_count: undefined,
      fb_post_likers_count: undefined,
      fb_post_shares_count: undefined,
      fb_post_reactors_count: undefined,
      fb_post_photo: undefined,
      fb_uploaded_photo: undefined,
      fb_post_publish_at_date: undefined,
      fb_post_url: undefined,
      fb_post_id: undefined,
      post_author: {
        twitter_user_id: undefined,
        twitter_created_at: undefined,
        twitter_full_name: undefined,
        twitter_username: undefined,
        twitter_location: undefined,
        twitter_favourites_count: undefined,
        twitter_followers_count: undefined,
        twitter_following_count: undefined,
        twitter_media_count: undefined,
        twitter_cover_photo: undefined,
        twitter_profile_picture: undefined,
        twitter_is_protected: undefined,
        twitter_statuses_count: undefined,
        twitter_description: undefined,
        linkedin_f_name: undefined,
        linkedin_l_name: undefined,
        title: undefined,
        linkedin_profile_picture: undefined,
        linkedin_profile_url: undefined,
        fb_full_name: undefined,
        fb_user_id: undefined,
        fb_gender: undefined,
        fb_profile_url: undefined,
      },
      tagged_profiles: [],
      activity_type: "post",
    },
  ],
  connections: {
    friends: undefined,
    following: {
      facebook: [
        {
          facebook_user_id: "100052394434128",
          facebook_full_name: "Blair Conklin",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/7/dc/5c746/7dc5c746-4586-454e-b6d6-48c9fb2955f3.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=6c20c3e1b35684c586de16488890d9d81912e9d34318019318907653ec041dac",
          facebook_profile_url: "https://www.facebook.com/100052394434128",
        },
        {
          facebook_user_id: "61567545718759",
          facebook_full_name: "Palm Tree Beach Club",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/5/8c/0ff83/58c0ff83-604d-44d7-b0e7-64c4d8fdd887.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=63e14a1dc3ee74d0da1e3048def42abcab04b16c2bf7509166ade1ed733319e6",
          facebook_profile_url: "https://www.facebook.com/61567545718759",
        },
        {
          facebook_user_id: "100064896483774",
          facebook_full_name: "Lacoste",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/3/d9/825d3/3d9825d3-4c7c-4cbd-a211-3bf2205b95ec.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e8c24838a594975327a1bfb7496edb38532627f6927b337c45091f36518e4d52",
          facebook_profile_url: "https://www.facebook.com/100064896483774",
        },
      ],
      instagram: undefined,
    },
  },
} as Person;

export const secondMergedPerson = {
  posts: [
    {
      twitter_post_likes_count: undefined,
      twitter_post_quoted_status: undefined,
      twitter_post_language: undefined,
      twitter_post_quotes_count: undefined,
      twitter_post_replies_count: undefined,
      twitter_post_retweets_count: undefined,
      twitter_post_retweeted_status: undefined,
      twitter_post_author_user_id: undefined,
      twitter_post_possibly_sensitive: undefined,
      twitter_post_card: undefined,
      twitter_post_photo: undefined,
      twitter_post_hashtags: undefined,
      twitter_post_symbols: undefined,
      twitter_post_urls: undefined,
      twitter_post_view_count: undefined,
      twitter_post_id: undefined,
      twitter_post_text: undefined,
      twitter_retweeted_post: undefined,
      twitter_quoted_post: undefined,
      verified: false,
      linkedin_post_text:
        "Microsoft 365 Copilot GCC general availability (GA) is Dec 13, 2024.\n\nLearn more: https://lnkd.in/dDrgV6ga\n\n#Copilot #M365Copilot",
      linkedin_post_publishment_date: "2024-12-12T17:16:10.242000",
      linkedin_post_comments_count: 0,
      linkedin_post_likes_count: 12,
      linkedin_post_shares_count: 0,
      linkedin_post_photo: undefined,
      linkedin_post_url:
        "https://www.linkedin.com/feed/update/urn:li:activity:7273022835621576704",
      reactions: [
        {
          linkedin_post_reaction_type: "LIKE",
          linkedin_post_reaction_type_count: 11,
        },
        {
          linkedin_post_reaction_type: "APPRECIATION",
          linkedin_post_reaction_type_count: 1,
        },
      ],
      post_reaction: undefined,
      shared_post: undefined,
      instagram_post_text: undefined,
      instagram_post_id: undefined,
      instagram_user_id: undefined,
      instagram_post_location: undefined,
      instagram_post_likes_count: undefined,
      post_likers: undefined,
      instagram_post_photo: undefined,
      fb_post_text: undefined,
      fb_post_language: undefined,
      fb_post_translated_to: undefined,
      post_translation: undefined,
      fb_post_external_webpages: undefined,
      fb_post_comments_count: undefined,
      fb_post_likers_count: undefined,
      fb_post_shares_count: undefined,
      fb_post_reactors_count: undefined,
      fb_post_photo: undefined,
      fb_uploaded_photo: undefined,
      fb_post_publish_at_date: undefined,
      fb_post_url: undefined,
      fb_post_id: undefined,
      post_author: {
        twitter_user_id: undefined,
        twitter_created_at: undefined,
        twitter_full_name: undefined,
        twitter_username: undefined,
        twitter_location: undefined,
        twitter_favourites_count: undefined,
        twitter_followers_count: undefined,
        twitter_following_count: undefined,
        twitter_media_count: undefined,
        twitter_cover_photo: undefined,
        twitter_profile_picture: undefined,
        twitter_is_protected: undefined,
        twitter_statuses_count: undefined,
        twitter_description: undefined,
        linkedin_f_name: undefined,
        linkedin_l_name: undefined,
        title: "Imagine, Experiment, and Adopt AI capabilities faster.",
        linkedin_profile_picture:
          "https://signaight-dev.s3.amazonaws.com/profile_photos/e/95/33cec/e9533cec-01af-4bb4-87fa-1875ec1723fd.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080032Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=04ec11f87b3e6a829248d91a9a8b58494c99bdd7da87897ac299d9272de8846e",
        linkedin_profile_url: "https://linkedin.com/in/mikemir",
        fb_full_name: undefined,
        fb_user_id: undefined,
        fb_gender: undefined,
        fb_profile_url: undefined,
      },
      tagged_profiles: [],
      activity_type: "post",
    },
  ],
  connections: {
    friends: undefined,
    following: {
      facebook: [
        {
          facebook_user_id: "100063725761434",
          facebook_full_name: "Live Winchester Place",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/9/fe/42ef6/9fe42ef6-f808-4c11-a90c-06a5f01df496.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d93b1dc1665dee2ca9921867b6027014f63af64ceee904f1c515d8a2b3d7b8c3",
          facebook_profile_url: "https://www.facebook.com/100063725761434",
        },
        {
          facebook_user_id: "100087308148072",
          facebook_full_name: "Profit Lounge",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/3/72/d1545/372d1545-1acb-4d70-9daf-db0ccf491772.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=04d35ba8faed7ff59ca0f792c5fc34640a0f1c541c8e7060743d5f5bf2974505",
          facebook_profile_url: "https://www.facebook.com/100087308148072",
        },
        {
          facebook_user_id: "100087549422876",
          facebook_full_name: "Gamze Gürdal",
          facebook_profile_picture:
            "https://signaight-dev.s3.amazonaws.com/profile_photos/f/ab/e80be/fabe80be-7eff-4bae-b860-6615c1e9a788.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQ2RRAMRNFZEN6BL5%2F20260109%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20260109T080033Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=f9718858ce9350fd998520c006a6af61b6f655f17620475f426d49ea6c1b2d4a",
          facebook_profile_url: "https://www.facebook.com/100087549422876",
        },
      ],
      instagram: undefined,
    },
  },
};
export const personWithLinkedinPosts = {
  ...defaultPerson,
  posts: [
    {
      twitter_post_likes_count: undefined,
      twitter_post_quoted_status: undefined,
      twitter_post_language: undefined,
      twitter_post_quotes_count: undefined,
      twitter_post_replies_count: undefined,
      twitter_post_retweets_count: undefined,
      twitter_post_retweeted_status: undefined,
      twitter_post_author_user_id: undefined,
      twitter_post_possibly_sensitive: undefined,
      twitter_post_card: undefined,
      twitter_post_photo: undefined,
      twitter_post_hashtags: undefined,
      twitter_post_symbols: undefined,
      twitter_post_urls: undefined,
      twitter_post_view_count: undefined,
      twitter_post_id: undefined,
      twitter_post_text: undefined,
      twitter_retweeted_post: undefined,
      twitter_quoted_post: undefined,
      verified: false,
      linkedin_post_text:
        'על חדשנות AI, שיווק יצירתי, וההבדל בין הסושיאל/מדיה לבין ההנדסה HANDS ON (לינקים ותמונות בתגובות)\n__\nאז השבוע, בעוד שיעור מרתק של Yael Steinhart\n על חדשנות,\n נכנסנו לעולמות של שיווק יצירתי, מטאפורי ואינטראקציוני.\nעלו דוגמאות פרסום שהיו לא פחות ממעוררות מחשבה של אנשי שיווק יצירתיים מאוד.\n\n ואז נזכרתי בפרסומת:\n שואב אבק ענק מעל מנהרה, "שואב" את התנועה.\n חזותית מדהימה.\n רציתי לשתף אותה בכיתה – ואז קלטתי:\n יש סיכוי טוב שזה בכלל נוצר על ידי AI.\nופה התחילו להתגלגל לי מחשבות.\nזה איכפת לי בכלל?\n\nאם פרסומת נועדה ליצור באזז,\nוהיא חד פעמית, אבל המסר אמור להיחקק ולהשתכפל\n האם באמת משנה אם היא אמיתית או לא?\nמצד אחד – לא.\n אבל מצד שני – איפה עובר הגבול?\n\nבהמשך השבוע עלתה פרסומת של משרד הכלכלה,\n על תעסוקה כחול-לבן בפס הייצור.\n גם שם – שימוש ב-AI מובהק- שמצהיר "אני האיש"\n שהוצג לציבור כאילו מדובר בצילומי שטח.\nתשובתם לביקורת – “זו הקדמה”.\nמה קורה כש"הקדמה" פוגשת את השטח?\n\nפה זה כבר נגע לי באופן אישי.\nכמהנדס, אני רגיל לראות מצגות נוצצות,\n תמונות “מרשימות” מפרויקטים או השווצה של עשינו ועשינו,\nגרפיקות חלקות שנועדו להרגיע, ולפעמים אפילו קטלוגים עם לכאורה מידע.\n\nכשאני יודע מה לשאול, ואיך לרדת לפרטים ולקלף שכבה אחת מתחת –\n לא תמיד מה שרואים הוא מה שקיים.\nולעיתים, זה אפילו מדאיג.\nלא תמיד אני אומר להם זאת בפנים- לרוב מצליב עם שניים שלושה מקורות מידע.\nוחמור מכך\nלא פעם הלקוחות שלי מקבלים תמונה שיווקית מושלמת, או דיווחים נפלאים מהשטח\nולוחצים אטומיים לאשר ההזמנה/ביצוע/אבן דרך.\n\nואז כששואלים את השאלות האמיתיות מגלים שהמציאות… אחרת לגמרי.\n ואז באות שלל של התנהגויות:\nלפעמים אומרים אבל זה כבר מוטמע, מאוחר מדי.\nאו\nאתה מעכב אותנו, כמה שאלות, תחתום כבר\nאו \nאבל אף פעם לא הצטרכנו להסביר את זה, או ככה תמיד אנחנו עושים- מי אתה שתשנה?\n\n ואז בא המכבש:\n “אל תעכב ותחתום כבר”\n “נמצא מישהו שיחתום במקומך”\n"מי אתה שלא תאשר?"\nושאר איומים מגוונים\n\nופה בא הנסיון ורשת החברים- לצרכי הפריית הידע, קולגיאליות ותמיכה \nשמלבד חברתי-היכולת שלי כמהנדס לרדת לפרטים,\nלנמק, לחשב או פשוט לדעת איפה לבדוק-\nלשים בצד את פן החברמן והיזם שטס קדימה\nולדרוש נתונים או תיעוד אמיתי מהשטח,\n ולא להסתפק במה שנראה יפה\n לעיתים ההבדל בין הצלחה לפיצוץ \n\nשדיברתי עם Danna Eviatar\n, האלופה ביצירתיות ומיתוג, שמכירה כבר הכל בשיווק.\n מצאתי עצמנו חושבים דווקא על אחריות.\nעל הגבול בין יצירתיות לפיקציה,\n ועל המקום שלי – כמהנדס, כאיש שטח,\n שמכיר גם את פיתוח וגם הפן הניהולי-עסקי,\n ויודע לשאול את השאלות הנכונות.\nבאם זה בחדשנות בדרך הגישה לפרויקט, או בחדשנות במוצרים שלעיתים הישום שלהם גלוי, או מאחורי הקלעים.\n\nבתקופה שבה כל תמונה יכולה להיות מזויפת \nתרבות היאללה צריך לרוץ קדימה-הרגישות הזו הופכת קריטית.\n\nהיכולת לעמוד על עמדה, נסיון, וכמובן לתרגם את הAI הזה שמסמלץ לנו נתונים או תמונות- ולדעת לדבר ללקוח בעיניים, או להיות היועץ הנכון בצוות הנכון.\nזה היתרון שלנו שלAI יקח הרבה מאוד זמן להחליף-אם בכלל\nההנדסה האנושית.\nעולה התהיה שפה אני חוקר- איפה זה פוגש את עולם היזמים.\nאיפה הדירקטוריונים או הבנקים, באמת מעוניינים לדעת ההבדל בין תמונה יפה לבין ניהול סיכונים. \n__\n- מה דעתכם על פרסום שנוצר ב-AI?\n -איפה עובר הגבול אצלכם?\n -יצא לכם להיתקל במשהו בסגנון?\n\nTel Aviv University - Coller School of Management\n#INNOVATION #ENGINEERING #BUSINESS #ENTREPRENEURSHIP',
      linkedin_post_publishment_date: "2025-12-14T12:35:29.541Z",
      linkedin_post_comments_count: 2,
      linkedin_post_likes_count: 9,
      linkedin_post_shares_count: 0,
      linkedin_post_photo: undefined,
      linkedin_post_url:
        "https://www.linkedin.com/feed/update/urn:li:activity:7405948547277361152",
      reactions: [
        {
          linkedin_post_reaction_type: "LIKE",
          linkedin_post_reaction_type_count: 9,
        },
      ],
      post_reaction: undefined,
      shared_post: undefined,
      instagram_post_text: undefined,
      instagram_post_id: undefined,
      instagram_user_id: undefined,
      instagram_post_location: undefined,
      instagram_post_likes_count: undefined,
      post_likers: undefined,
      instagram_post_photo: undefined,
      fb_post_text: undefined,
      fb_post_language: undefined,
      fb_post_translated_to: undefined,
      post_translation: undefined,
      fb_post_external_webpages: undefined,
      fb_post_comments_count: undefined,
      fb_post_likers_count: undefined,
      fb_post_shares_count: undefined,
      fb_post_reactors_count: undefined,
      fb_post_photo: undefined,
      fb_uploaded_photo: undefined,
      fb_post_publish_at_date: undefined,
      fb_post_url: undefined,
      fb_post_id: undefined,
      post_author: {
        twitter_user_id: undefined,
        twitter_created_at: undefined,
        twitter_full_name: undefined,
        twitter_username: undefined,
        twitter_location: undefined,
        twitter_favourites_count: undefined,
        twitter_followers_count: undefined,
        twitter_following_count: undefined,
        twitter_media_count: undefined,
        twitter_cover_photo: undefined,
        twitter_profile_picture: undefined,
        twitter_is_protected: undefined,
        twitter_statuses_count: undefined,
        twitter_description: undefined,
        linkedin_f_name: undefined,
        linkedin_l_name: undefined,
        title:
          "Cert. Electrical & Energy Engineer | Technical ESG Business Consultant | Founder of SGE Consults | Impact Innovation | Value Purposed BizDev",
        linkedin_profile_picture:
          "s3://signaight-dev/profile_photos/4/c6/440c2/4c6440c2-5692-4ef4-85fb-b1bfe35e9168.jpg",
        linkedin_profile_url: "https://linkedin.com/in/gilshua",
        fb_full_name: undefined,
        fb_user_id: undefined,
        fb_gender: undefined,
        fb_profile_url: undefined,
      },
      tagged_profiles: [],
      activity_type: "post",
    },
  ],
} as Person;
export const personWithFBPhotoPosts = {
  ...defaultPerson,
  posts: [
    {
      twitter_post_likes_count: undefined,
      twitter_post_quoted_status: undefined,
      twitter_post_language: undefined,
      twitter_post_quotes_count: undefined,
      twitter_post_replies_count: undefined,
      twitter_post_retweets_count: undefined,
      twitter_post_retweeted_status: undefined,
      twitter_post_author_user_id: undefined,
      twitter_post_possibly_sensitive: undefined,
      twitter_post_card: undefined,
      twitter_post_photo: undefined,
      twitter_post_hashtags: undefined,
      twitter_post_symbols: undefined,
      twitter_post_urls: undefined,
      twitter_post_view_count: undefined,
      twitter_post_id: undefined,
      twitter_post_text: undefined,
      twitter_retweeted_post: undefined,
      twitter_quoted_post: undefined,
      verified: false,
      linkedin_post_text: undefined,
      linkedin_post_publishment_date: undefined,
      linkedin_post_comments_count: undefined,
      linkedin_post_likes_count: undefined,
      linkedin_post_shares_count: undefined,
      linkedin_post_photo: undefined,
      linkedin_post_url: undefined,
      reactions: undefined,
      post_reaction: undefined,
      shared_post: undefined,
      instagram_post_text: undefined,
      instagram_post_id: undefined,
      instagram_user_id: undefined,
      instagram_post_location: undefined,
      instagram_post_likes_count: undefined,
      post_likers: undefined,
      instagram_post_photo: undefined,
      fb_post_text: undefined,
      fb_post_language: undefined,
      fb_post_translated_to: undefined,
      post_translation: undefined,
      fb_post_external_webpages: undefined,
      fb_post_comments_count: undefined,
      fb_post_likers_count: undefined,
      fb_post_shares_count: undefined,
      fb_post_reactors_count: undefined,
      fb_post_photo: undefined,
      fb_uploaded_photo: {
        fb_photo_id: "647557236187357",
        fb_photo_likes_count: 9,
        fb_photo_reactions_count: 0,
        fb_photo_comments_count: undefined,
        fb_photo: {
          url: "s3://signaight-dev/profile_photos/0/86/f285a/086f285a-f0e6-4599-bb1c-7df997de5d8b.jpg",
          width: undefined,
          height: null,
        },
        fb_photo_lq: undefined,
        fb_photo_mq: undefined,
        fb_photo_hq: null,
      },
      fb_post_publish_at_date: undefined,
      fb_post_url: undefined,
      fb_post_id: undefined,
      post_author: undefined,
      tagged_profiles: undefined,
      activity_type: "post",
    },
  ],
} as Person;
